service: hidden-p-detector-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# package:
#   patterns:
#     - "handler.py"
#     - "!./**"

functions:
  telegram:
    handler: handler.telegram
    events:
      - httpApi:
          path: /users/create
          method: get
    environment:
      P: penis

plugins:
  - serverless-python-requirements
