service: hidden-word-detector

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: python3.10
  architecture: arm64
  stage: development

functions:
  telegram:
    handler: handler.telegram
    environment:
      SECRET: ${env:SECRET}
      TELEGRAM_TOKEN: ${env:TOKEN}
      WORD: ${env:WORD}
    events:
      - http: POST /webhook

plugins:
  - serverless-python-requirements
