service: hidden-word-detector

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: python3.10
  architecture: arm64
  stage: development

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    GlobalTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  telegram:
    handler: handler.telegram
    events:
      - http: POST /webhook
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynanmodb:Scan
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt: [UserTable, Arn]
          - Fn::GetAtt: [GlobalTable, Arn]
    environment:
      SECRET: ${env:SECRET}
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      WORD: ${env:WORD}
      USER_TABLE:
        Ref: UserTable
      GLOBAL_TABLE:
        Ref: GlobalTable

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
