service: hidden-p-detector-bot

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  runtime: python3.10
  architecture: arm64
  stage: development

functions:
  telegram:
    handler: handler.telegram
    environment:
      HIDDEN: penis
    events:
      - httpApi:
          path: /users/create
          method: get

plugins:
  - serverless-python-requirements
