service: freudian-slip

frameworkVersion: "3"

configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: python3.10
  architecture: arm64
  stage: development

resources:
  Resources:
    UserWordTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UserNumberTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    GlobalWordTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    GlobalNumberTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  telegram:
    handler: handler.telegram
    events:
      - http: POST /webhook
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:UpdateItem
        Resource:
          - Fn::GetAtt: [UserNumberTable, Arn]
          - Fn::GetAtt: [GlobalNumberTable, Arn]
          - Fn::GetAtt: [UserWordTable, Arn]
          - Fn::GetAtt: [GlobalWordTable, Arn]
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      SECRET: ${env:SECRET}
      NUMBER: ${env:NUMBER}
      WORD: ${env:WORD}
      USER_NUMBER_TABLE:
        Ref: UserNumberTable
      GLOBAL_NUMBER_TABLE:
        Ref: GlobalNumberTable
      USER_WORD_TABLE:
        Ref: UserWordTable
      GLOBAL_WORD_TABLE:
        Ref: GlobalWordTable

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
